branch: 'main'
repoUrl: 'https://github.com/Suchismita14/nginx-install.git'
approvalMessage: 'Do you want to proceed with Ansible Playbook execution?'
approvalButton: 'Proceed'
playbookPath: 'install.yml'
inventory_file: 'inventory.ini'
slackChannel: 'jk'
successMessage: 'Pipeline Job Succeeded'
failureMessage: 'Pipeline Job Failed'
unstableMessage: 'Pipeline Job is Unstable'
