branch: 'main'
repoUrl: 'https://github.com/G1tGeek/kafka.git'
approvalMessage: 'Do you want to proceed with Ansible Playbook execution?'
approvalButton: 'Proceed'
playbookPath: 'install.yml'
slackChannel: 'jk'
successMessage: 'Pipeline Job Succeeded'
failureMessage: 'Pipeline Job Failed'
unstableMessage: 'Pipeline Job is Unstable'
